apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  labels:
    app.kubernetes.io/name: mysql-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-rbac
  labels:
    app.kubernetes.io/name: mysql-operator
subjects:
  - kind: ServiceAccount
    name: mysql-operator
    namespace: grds
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
